---
- name: Install and start Apache web server
  hosts: all
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: true

