---
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes

- hosts: web_servers
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Apache2 and PHP packages for Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
 
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package(Ubuntu)
    apt:
      name: mariadb-server
      state: latest

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
          name: samba
          state: latest
