---
- name: Update and Upgrade all servers
  hosts: all
  become: true
  tasks:
    - name: Install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      tags: always

- name: Configure Web Servers
  hosts: web_servers
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
      tags: apache,apache2,ubuntu

    - name: Install Apache2 and PHP packages for Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest

    - name: Copy default HTML file for site
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      tags: apache,apache2,ubuntu

- name: Configure Workstations
  hosts: workstations
  become: true
  tasks:
    - name: Install unzip
      package:
        name: unzip

    - name: Install Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
        dest: /tmp/terraform.zip
        validate_certs: yes
      become: true
      tags: terraform
      notify: Extract Terraform

  handlers:
    - name: Extract Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
      become: true
      tags: terraform

- name: Configure Database Servers
  hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      tags: ubuntu,db,mariadb

- name: Configure File Servers
  hosts: file_servers
  become: true
  tasks:
    - name: Install Samba package
      package:
        name: samba
        state: latest
      tags: samba

